# © 2025 Maximilian Marx
# SPDX-FileContributor: Maximilian Marx
#
# SPDX-License-Identifier: EUPL-1.2

[advisories]
ignore = ["RUSTSEC-2024-0436"]

[bans]
multiple-versions = "allow"
wildcards = "warn"

[licenses]
unused-allowed-license = "warn"
allow = [
  "EUPL-1.2",
  "MIT",
  "Apache-2.0",
  "Unicode-3.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Unlicense",
  "BSL-1.0",
  "MPL-2.0",
  "Zlib",
]
