# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/consumer/db/schema.rs"
patch_file = "schema.patch"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/home/mmarx/proj/rust/kommemeorate/migrations"
