name: Build with nix

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  RUST_LOG: debug

jobs:
  check:
    name: Ensure that the nix flake evaluates and run the checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            keep-outputs = true
            keep-derivations = true
      - name: Restore and save the Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: kommemeorate-nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: kommemeorate-nix-${{ runner.os }}-
          gc-max-store-size-linux: 2.5G
          purge: true
          purge-prefixes: kommemeorate-nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never
      - run: nix flake check
      - name: Build and collect garbage
        run: |
          nix build .\#kommemeorate
          nix-store --optimise
          nix-collect-garbage -d
